language: python

python:
  - 3.6

env:
  - DJANGO=2.1

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433


install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - flake8
  - ./manage.py makemigrations
  - ./manage.py migrate
  - ./manage.py test
