version: '3'

services:
  db:
     image: postgres
     ports:
     - "5432:5432"
     volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    container_name: friends_connect_server
    build: .
    command:
      python /code/manage.py migrate --noinput
    command:
      python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
       - db
    env_file:
    - email.env

volumes:
  postgres_data: