# Generated by Django 2.1 on 2018-09-21 02:33
from _overlapped import NULL

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='User_Activity_id',
            field=models.ForeignKey(default=NULL, on_delete=django.db.models.deletion.CASCADE, to='App.UserModel'),
            preserve_default=False,
        ),
    ]
