# Generated by Django 2.1 on 2018-10-14 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0005_remove_usermodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='User_Activity_id',
        ),
        migrations.AddField(
            model_name='activity',
            name='user_activity_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
